### ISSUE TITLE
Error on `quarto use template fredguth/tufte-inspired`

### ISSUE THREAD

**Issue by cwickham** [fredguth/tufte-inspired#1]
On `quarto use template fredguth/tufte-inspired`, I'm getting the error:
```
ERROR: Failed to resolve referenced filter citing-html.lua - path does not exist.
```

Looks like the `html` format requires it, but it isn't in this extension:

https://github.com/fredguth/tufte-inspired/blob/8de3132ec17013eaab7634db23063413d893eac8/_extensions/tufte-inspired/_extension.yml#L26

**Comment by fredguth** [comment]
I am taking a look right now.

**Comment by fredguth** [comment]
error in my .gitignore

**Comment by fredguth** [comment]
Could you test now?

**Comment by cwickham** [comment]
Working without error!

**Comment by cwickham** [comment]
I'm also finding that for the template `index.qmd` to render I'm needing to remove the leading slash on the image paths, e.g. using:
```
(Images/et_midjourney_transparent.png)
```
instead of,
```
(/Images/et_midjourney_transparent.png)
```

Otherwise working great!

**Comment by cwickham** [comment]
Just a heads up, I'm planning to mention your extension at posit::conf next week.

**Comment by fredguth** [comment]
Please let me know when it is, I will be glad to watch it online (I am almost always on Shiny's discord if you need to reach me).
